# Generated by Django 3.2.13 on 2022-06-09 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1990-06-17'),
            preserve_default=False,
        ),
    ]
